name: Mattermost Post WebHook
description: Post a message to Mattermost thanks to a WebHook URL

inputs:
  webhook-url:
    description: WebHook URL to post message to
    required: true
    type: string

  text:
    description: Text message that should be posted to Mattermost
    required: true
    type: string

  title:
    description: Main message title
    type: string
    required: false

  color:
    description: Message color
    type: string
    required: false
    default: '#47ba04'

runs:
  using: 'node20'
  main: 'dist/index.js'
